// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: signaling.proto

package signaling

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*ClientMessage_Register
	//	*ClientMessage_Result
	//	*ClientMessage_Heartbeat
	Content       isClientMessage_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_signaling_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetContent() isClientMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ClientMessage) GetRegister() *ClientRegister {
	if x != nil {
		if x, ok := x.Content.(*ClientMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *ClientMessage) GetResult() *CommandResult {
	if x != nil {
		if x, ok := x.Content.(*ClientMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ClientMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Content.(*ClientMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isClientMessage_Content interface {
	isClientMessage_Content()
}

type ClientMessage_Register struct {
	Register *ClientRegister `protobuf:"bytes,1,opt,name=register,proto3,oneof"` // 客户端注册
}

type ClientMessage_Result struct {
	Result *CommandResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"` // 命令执行结果
}

type ClientMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"` // 心跳包
}

func (*ClientMessage_Register) isClientMessage_Content() {}

func (*ClientMessage_Result) isClientMessage_Content() {}

func (*ClientMessage_Heartbeat) isClientMessage_Content() {}

type ServerCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgID         int64                  `protobuf:"varint,1,opt,name=MsgID,proto3" json:"MsgID,omitempty"`    // 命令唯一ID
	Method        string                 `protobuf:"bytes,2,opt,name=Method,proto3" json:"Method,omitempty"`   // 执行动作
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // 附加数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerCommand) Reset() {
	*x = ServerCommand{}
	mi := &file_signaling_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCommand) ProtoMessage() {}

func (x *ServerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCommand.ProtoReflect.Descriptor instead.
func (*ServerCommand) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{1}
}

func (x *ServerCommand) GetMsgID() int64 {
	if x != nil {
		return x.MsgID
	}
	return 0
}

func (x *ServerCommand) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ServerCommand) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ClientRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // 客户端唯一标识
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                   // 客户端版本
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRegister) Reset() {
	*x = ClientRegister{}
	mi := &file_signaling_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRegister) ProtoMessage() {}

func (x *ClientRegister) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRegister.ProtoReflect.Descriptor instead.
func (*ClientRegister) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{2}
}

func (x *ClientRegister) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientRegister) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgID         int64                  `protobuf:"varint,1,opt,name=MsgID,proto3" json:"MsgID,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_signaling_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{3}
}

func (x *CommandResult) GetMsgID() int64 {
	if x != nil {
		return x.MsgID
	}
	return 0
}

func (x *CommandResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResult) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_signaling_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type IpcEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // 客户端唯一标识
	IpcId         string                 `protobuf:"bytes,2,opt,name=ipc_id,json=ipcId,proto3" json:"ipc_id,omitempty"`          // IPC MsgID
	Event         string                 `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpcEventRequest) Reset() {
	*x = IpcEventRequest{}
	mi := &file_signaling_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpcEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpcEventRequest) ProtoMessage() {}

func (x *IpcEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpcEventRequest.ProtoReflect.Descriptor instead.
func (*IpcEventRequest) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{5}
}

func (x *IpcEventRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *IpcEventRequest) GetIpcId() string {
	if x != nil {
		return x.IpcId
	}
	return ""
}

func (x *IpcEventRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

type IpcEventAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 处理结果是否成功
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`          // 服务端的反馈信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpcEventAck) Reset() {
	*x = IpcEventAck{}
	mi := &file_signaling_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpcEventAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpcEventAck) ProtoMessage() {}

func (x *IpcEventAck) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpcEventAck.ProtoReflect.Descriptor instead.
func (*IpcEventAck) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{6}
}

func (x *IpcEventAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IpcEventAck) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type IpcInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	IpcId         string                 `protobuf:"bytes,2,opt,name=ipc_id,json=ipcId,proto3" json:"ipc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpcInviteRequest) Reset() {
	*x = IpcInviteRequest{}
	mi := &file_signaling_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpcInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpcInviteRequest) ProtoMessage() {}

func (x *IpcInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpcInviteRequest.ProtoReflect.Descriptor instead.
func (*IpcInviteRequest) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{7}
}

func (x *IpcInviteRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *IpcInviteRequest) GetIpcId() string {
	if x != nil {
		return x.IpcId
	}
	return ""
}

type IpcInviteAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ZlmIp         string                 `protobuf:"bytes,2,opt,name=zlm_ip,json=zlmIp,proto3" json:"zlm_ip,omitempty"`
	ZlmPort       int64                  `protobuf:"varint,3,opt,name=zlm_port,json=zlmPort,proto3" json:"zlm_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpcInviteAck) Reset() {
	*x = IpcInviteAck{}
	mi := &file_signaling_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpcInviteAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpcInviteAck) ProtoMessage() {}

func (x *IpcInviteAck) ProtoReflect() protoreflect.Message {
	mi := &file_signaling_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpcInviteAck.ProtoReflect.Descriptor instead.
func (*IpcInviteAck) Descriptor() ([]byte, []int) {
	return file_signaling_proto_rawDescGZIP(), []int{8}
}

func (x *IpcInviteAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IpcInviteAck) GetZlmIp() string {
	if x != nil {
		return x.ZlmIp
	}
	return ""
}

func (x *IpcInviteAck) GetZlmPort() int64 {
	if x != nil {
		return x.ZlmPort
	}
	return 0
}

var File_signaling_proto protoreflect.FileDescriptor

const file_signaling_proto_rawDesc = "" +
	"\n" +
	"\x0fsignaling.proto\x12\tsignaling\"\xbd\x01\n" +
	"\rClientMessage\x127\n" +
	"\bregister\x18\x01 \x01(\v2\x19.signaling.ClientRegisterH\x00R\bregister\x122\n" +
	"\x06result\x18\x02 \x01(\v2\x18.signaling.CommandResultH\x00R\x06result\x124\n" +
	"\theartbeat\x18\x03 \x01(\v2\x14.signaling.HeartbeatH\x00R\theartbeatB\t\n" +
	"\acontent\"W\n" +
	"\rServerCommand\x12\x14\n" +
	"\x05MsgID\x18\x01 \x01(\x03R\x05MsgID\x12\x16\n" +
	"\x06Method\x18\x02 \x01(\tR\x06Method\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"G\n" +
	"\x0eClientRegister\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"Y\n" +
	"\rCommandResult\x12\x14\n" +
	"\x05MsgID\x18\x01 \x01(\x03R\x05MsgID\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\")\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"[\n" +
	"\x0fIpcEventRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x15\n" +
	"\x06ipc_id\x18\x02 \x01(\tR\x05ipcId\x12\x14\n" +
	"\x05event\x18\x03 \x01(\tR\x05event\"9\n" +
	"\vIpcEventAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"F\n" +
	"\x10IpcInviteRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x15\n" +
	"\x06ipc_id\x18\x02 \x01(\tR\x05ipcId\"Z\n" +
	"\fIpcInviteAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x15\n" +
	"\x06zlm_ip\x18\x02 \x01(\tR\x05zlmIp\x12\x19\n" +
	"\bzlm_port\x18\x03 \x01(\x03R\azlmPort2\xe0\x01\n" +
	"\n" +
	"SipService\x12I\n" +
	"\rStreamChannel\x12\x18.signaling.ClientMessage\x1a\x18.signaling.ServerCommand\"\x00(\x010\x01\x12A\n" +
	"\vIpcEventReq\x12\x1a.signaling.IpcEventRequest\x1a\x16.signaling.IpcEventAck\x12D\n" +
	"\fIpcInviteReq\x12\x1b.signaling.IpcInviteRequest\x1a\x17.signaling.IpcInviteAckB\rZ\v./signalingb\x06proto3"

var (
	file_signaling_proto_rawDescOnce sync.Once
	file_signaling_proto_rawDescData []byte
)

func file_signaling_proto_rawDescGZIP() []byte {
	file_signaling_proto_rawDescOnce.Do(func() {
		file_signaling_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signaling_proto_rawDesc), len(file_signaling_proto_rawDesc)))
	})
	return file_signaling_proto_rawDescData
}

var file_signaling_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_signaling_proto_goTypes = []any{
	(*ClientMessage)(nil),    // 0: signaling.ClientMessage
	(*ServerCommand)(nil),    // 1: signaling.ServerCommand
	(*ClientRegister)(nil),   // 2: signaling.ClientRegister
	(*CommandResult)(nil),    // 3: signaling.CommandResult
	(*Heartbeat)(nil),        // 4: signaling.Heartbeat
	(*IpcEventRequest)(nil),  // 5: signaling.IpcEventRequest
	(*IpcEventAck)(nil),      // 6: signaling.IpcEventAck
	(*IpcInviteRequest)(nil), // 7: signaling.IpcInviteRequest
	(*IpcInviteAck)(nil),     // 8: signaling.IpcInviteAck
}
var file_signaling_proto_depIdxs = []int32{
	2, // 0: signaling.ClientMessage.register:type_name -> signaling.ClientRegister
	3, // 1: signaling.ClientMessage.result:type_name -> signaling.CommandResult
	4, // 2: signaling.ClientMessage.heartbeat:type_name -> signaling.Heartbeat
	0, // 3: signaling.SipService.StreamChannel:input_type -> signaling.ClientMessage
	5, // 4: signaling.SipService.IpcEventReq:input_type -> signaling.IpcEventRequest
	7, // 5: signaling.SipService.IpcInviteReq:input_type -> signaling.IpcInviteRequest
	1, // 6: signaling.SipService.StreamChannel:output_type -> signaling.ServerCommand
	6, // 7: signaling.SipService.IpcEventReq:output_type -> signaling.IpcEventAck
	8, // 8: signaling.SipService.IpcInviteReq:output_type -> signaling.IpcInviteAck
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_signaling_proto_init() }
func file_signaling_proto_init() {
	if File_signaling_proto != nil {
		return
	}
	file_signaling_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_Register)(nil),
		(*ClientMessage_Result)(nil),
		(*ClientMessage_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signaling_proto_rawDesc), len(file_signaling_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_signaling_proto_goTypes,
		DependencyIndexes: file_signaling_proto_depIdxs,
		MessageInfos:      file_signaling_proto_msgTypes,
	}.Build()
	File_signaling_proto = out.File
	file_signaling_proto_goTypes = nil
	file_signaling_proto_depIdxs = nil
}
